import type { Metadata } from 'next'
import './globals.scss'
import Header from '@/components/Header'
import Accordion from '@/components/Accordion';

export const metadata: Metadata = {
  title: 'Phenom',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Accordion />
      </body>
    </html>
  )
}
