import type { Metadata } from 'next'
import './globals.scss'
import Head from 'next/head';
import Header from '@/components/Header'
import Dropdown from '@/components/Dropdown';
import Accordion from '@/components/Accordion';

export const metadata: Metadata = {
  title: 'Phenom',

  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
      </Head>
      <body>
        <Header />
        {children}
        <Accordion />
      </body>
    </html>
  )
}
